--
-- Food groups for mobs
--

feed = {}

feed.plants = {
	"plant:barley_1",
	"plant:barley_2",
	"plant:barley_3",
	"plant:barley_4",
	"plant:barley_5",
	"plant:barley_6",
	"plant:barley_7",
	"plant:barley_8",
	"plant:beans",
	"plant:beans_1",
	"plant:beans_2",
	"plant:beans_3",
	"plant:beet",
	"plant:beet_1",
	"plant:beet_2",
	"plant:beet_3",
	"plant:blackberry",
	"plant:blackberry_fruit",
	"plant:carrot",
	"plant:carrot_1",
	"plant:carrot_2",
	"plant:carrot_3",
	"plant:fathen",
	"plant:fathen_1",
	"plant:fathen_2",
	"plant:fathen_3",
	"plant:golden_grass_1",
	"plant:golden_grass_2",
	"plant:golden_grass_3",
	"plant:golden_grass_4",
	"plant:golden_grass_5",
	"plant:grass_1",
	"plant:grass_2",
	"plant:grass_3",
	"plant:grass_4",
	"plant:grass_5",
	"plant:heath_gold",
	"plant:heath_green",
	"plant:heath_purple",
	"plant:heath_red",
	"plant:heath_sandwort",
	"plant:heath_saxifrage_purple",
	"plant:junglegrass",
	"plant:maize_1",
	"plant:maize_2",
	"plant:maize_3",
	"plant:maize_4",
	"plant:maize_5",
	"plant:maize_6",
	"plant:maize_7",
	"plant:maize_8",
	"plant:oats_1",
	"plant:oats_2",
	"plant:oats_3",
	"plant:oats_4",
	"plant:oats_5",
	"plant:oats_6",
	"plant:oats_7",
	"plant:oats_8",
	"plant:onion_1",
	"plant:onion_2",
	"plant:onion_3",
	"plant:onion_4",
	"plant:onion_5",
	"plant:seaweed",
	"plant:strawberry",
	"plant:strawberry_fruit",
	"plant:wheat_1",
	"plant:wheat_2",
	"plant:wheat_3",
	"plant:wheat_4",
	"plant:wheat_5",
	"plant:wheat_6",
	"plant:wheat_7",
	"plant:wheat_8",
}

feed.grasses = {
	"plant:barley_1",
	"plant:barley_2",
	"plant:barley_3",
	"plant:barley_4",
	"plant:barley_5",
	"plant:barley_6",
	"plant:barley_7",
	"plant:barley_8",
	"plant:golden_grass_1",
	"plant:golden_grass_2",
	"plant:golden_grass_3",
	"plant:golden_grass_4",
	"plant:golden_grass_5",
	"plant:grass_1",
	"plant:grass_2",
	"plant:grass_3",
	"plant:grass_4",
	"plant:grass_5",
	"plant:maize_1",
	"plant:maize_2",
	"plant:maize_3",
	"plant:maize_4",
	"plant:maize_5",
	"plant:maize_6",
	"plant:maize_7",
	"plant:maize_8",
	"plant:oats_1",
	"plant:oats_2",
	"plant:oats_3",
	"plant:oats_4",
	"plant:oats_5",
	"plant:oats_6",
	"plant:oats_7",
	"plant:oats_8",
	"plant:wheat_1",
	"plant:wheat_2",
	"plant:wheat_3",
	"plant:wheat_4",
	"plant:wheat_5",
	"plant:wheat_6",
	"plant:wheat_7",
	"plant:wheat_8"
}

feed.grazing = {"plant:grass_3", "plant:grass_4", "plant:grass_5", "plant:wheat_8", "plant:barley_8", "plant:maize_8", "plant:oats_8", "flowers:seaweed"}

feed.seed = {"plant:wheat", "plant:barley", "plant:oats", "plant:maize"}

feed.bunny = {"plant:carrot_3", "plant:carrot"}

feed.kitten = {"mobs:rat", "fishing:fish_raw", "mobs_fish:clownfish", "mobs_fish:tropical", "mobs_animal:rat", "group:food_fish_raw", "mobs_fish:tropical", "xocean:fish_edible"}

feed.npc = {"food:bread", "mobs:meat", "mineral:diamond_gem", "food:cake", "food:fruitcake", "food:soup_chicken_cooked", "food:soup_vegetable_cooked", "food:stew_meat_cooked", "food:stew_vegetable_cooked"}

feed.sheep = {"plant:hay", "group:grass"}

feed.pig = {"tree:apple", "tree:acorn", "plant:beetroot", "plant:carrot", "plant:turnip"}
