-- Grailtest 5 --
-- mods/equipment_pack/tool/aliases.lua

minetest.register_alias("default:axe_bronze", "tool:axe_bronze")
minetest.register_alias("default:axe_diamond", "tool:axe_diamond")
minetest.register_alias("default:axe_mese", "tool:axe_mithril")
minetest.register_alias("default:axe_steel", "tool:axe_steel")
minetest.register_alias("SteelAxe", "tool:axe_steel")
minetest.register_alias("default:axe_stone", "tool:axe_stone")
minetest.register_alias("STAxe", "tool:axe_stone")
minetest.register_alias("default:axe_wood", "tool:axe_wood")
minetest.register_alias("WAxe", "tool:axe_wood")
minetest.register_alias("default:pick_bronze", "tool:pick_bronze")
minetest.register_alias("default:pick_diamond", "tool:pick_diamond")
minetest.register_alias("default:pick_mese", "tool:pick_mithril")
minetest.register_alias("MesePick", "tool:pick_mithril")
minetest.register_alias("default:pick_steel", "tool:pick_steel")
minetest.register_alias("SteelPick", "tool:pick_steel")
minetest.register_alias("default:pick_stone", "tool:pick_stone")
minetest.register_alias("STPick", "tool:pick_stone")
minetest.register_alias("default:pick_wood", "tool:pick_wood")
minetest.register_alias("WPick", "tool:pick_wood")
minetest.register_alias("default:shovel_bronze", "tool:shovel_bronze")
minetest.register_alias("default:shovel_diamond", "tool:shovel_diamond")
minetest.register_alias("default:shovel_mese", "tool:shovel_mithril")
minetest.register_alias("default:shovel_steel", "tool:shovel_steel")
minetest.register_alias("SteelShovel", "tool:shovel_steel")
minetest.register_alias("default:shovel_stone", "tool:shovel_stone")
minetest.register_alias("STShovel", "tool:shovel_stone")
minetest.register_alias("default:shovel_wood", "tool:shovel_wood")
minetest.register_alias("WShovel", "tool:shovel_wood")
minetest.register_alias("default:sword_bronze", "tool:sword_bronze")
minetest.register_alias("default:sword_diamond", "tool:sword_diamond")
minetest.register_alias("default:sword_mese", "tool:sword_mithril")
minetest.register_alias("default:sword_steel", "tool:sword_steel")
minetest.register_alias("SteelSword", "tool:sword_steel")
minetest.register_alias("default:sword_stone", "tool:sword_stone")
minetest.register_alias("STSword", "tool:sword_stone")
minetest.register_alias("default:sword_wood", "tool:sword_wood")
minetest.register_alias("farming:hoe_bronze", "tool:hoe_bronze")
minetest.register_alias("farming:hoe_diamond", "tool:hoe_copper")
minetest.register_alias("farming:hoe_mese", "tool:hoe_mithril")
minetest.register_alias("farming:hoe_steel", "tool:hoe_steel")
minetest.register_alias("farming:hoe_stone", "tool:hoe_stone")
minetest.register_alias("farming:hoe_wood", "tool:hoe_wood")


