minetest.register_alias("brick", "material:brick")
minetest.register_alias("clay_brick", "material:clay_brick")
minetest.register_alias("default:brick", "material:brick")
minetest.register_alias("default:desert_stone_brick", "material:desert_stone_brick")
minetest.register_alias("default:glass", "material:glass")
minetest.register_alias("default:junglewood", "material:junglewood")
minetest.register_alias("default:obsidian_glass", "material:obsidian_glass")
minetest.register_alias("default:paper", "material:paper")
minetest.register_alias("default:sandstone_brick", "material:sandstone_brick")
minetest.register_alias("default:stick", "material:stick")
minetest.register_alias("default:stone_brick", "material:stone_brick")
minetest.register_alias("default:stonebrick", "material:stone_brick")
minetest.register_alias("default:wood", "material:wood")
minetest.register_alias("farming:string", "material:string")
minetest.register_alias("glass", "material:glass")
minetest.register_alias("paper", "material:paper")
minetest.register_alias("Stick", "material:stick")
minetest.register_alias("string", "material:string")
minetest.register_alias("wood", "material:wood")

-- Backwards compatibility with jordach's 16-color wool mod
minetest.register_alias("wool:black", "material:fabric_black")
minetest.register_alias("wool:blue", "material:fabric_blue")
minetest.register_alias("wool:brown", "material:fabric_brown")
minetest.register_alias("wool:cyan", "material:fabric_cyan")
minetest.register_alias("wool:dark_blue", "material:fabric_blue")
minetest.register_alias("wool:dark_green", "material:fabric_dark_green")
minetest.register_alias("wool:dark_grey", "material:fabric_dark_grey")
minetest.register_alias("wool:gold", "material:fabric_yellow")
minetest.register_alias("wool:green", "material:fabric_green")
minetest.register_alias("wool:grey", "material:fabric_grey")
minetest.register_alias("wool:magenta", "material:fabric_magenta")
minetest.register_alias("wool:magenta", "material:fabric_pink")
minetest.register_alias("wool:orange", "material:fabric_orange")
minetest.register_alias("wool:pink", "material:fabric_pink")
minetest.register_alias("wool:red", "material:fabric_red")
minetest.register_alias("wool:violet", "material:fabric_violet")
minetest.register_alias("wool:white", "material:fabric_white")
minetest.register_alias("wool:yellow", "material:fabric_yellow")


