-- Grailtest 5 --
-- mods/element/aliases.lua --
-- Provides aliases for most default items

minetest.register_alias("cloud", "element:cloud")
minetest.register_alias("cobble", "element:cobble")
minetest.register_alias("dirt", "element:dirt")
minetest.register_alias("dirt_with_grass", "element:dirt_with_grass")
minetest.register_alias("dirt_with_grass_footsteps", "element:dirt_with_grass_footsteps")
minetest.register_alias("gravel", "element:gravel")
minetest.register_alias("lava_flowing", "element:lava_flowing")
minetest.register_alias("lava_source", "element:lava_source")
minetest.register_alias("mossycobble", "element:mossycobble")
minetest.register_alias("sand", "element:sand")
minetest.register_alias("sandstone", "element:sandstone")
minetest.register_alias("snow", "element:snow")
minetest.register_alias("stone", "element:stone")
minetest.register_alias("water_flowing", "element:water_flowing")
minetest.register_alias("water_source", "element:water_source")

minetest.register_alias("mapgen_cobble", "element:cobble")
minetest.register_alias("mapgen_desert_sand", "element:desert_sand")
minetest.register_alias("mapgen_desert_stone", "element:desert_stone")
minetest.register_alias("mapgen_dirt", "element:dirt")
minetest.register_alias("mapgen_dirt_with_grass", "element:dirt_with_grass")
minetest.register_alias("mapgen_dirt_with_snow", "element:dirt_with_snow")
minetest.register_alias("mapgen_gravel", "element:gravel")
minetest.register_alias("mapgen_ice", "element:ice")
minetest.register_alias("mapgen_lava_source", "element:lava_source")
minetest.register_alias("mapgen_mossycobble", "element:mossycobble")
minetest.register_alias("mapgen_river_water_source", "element:river_water_source")
minetest.register_alias("mapgen_sand", "element:sand")
minetest.register_alias("mapgen_sandstone", "element:sandstone")
minetest.register_alias("mapgen_snowblock", "element:snowblock")
minetest.register_alias("mapgen_snow", "element:snow")
minetest.register_alias("mapgen_stone", "element:stone")
minetest.register_alias("mapgen_water_source", "element:water_source")

-- legacy aliases for compatibility with MTG

minetest.register_alias("default:cloud", "element:cloud")
minetest.register_alias("default:desert_sand", "element:desert_sand")
minetest.register_alias("default:desert_stone", "element:desert_stone")
minetest.register_alias("default:dirt", "element:dirt")
minetest.register_alias("default:dirt_with_dry_grass", "element:dirt_with_dry_grass")
minetest.register_alias("default:dirt_with_grass", "element:dirt_with_grass")
minetest.register_alias("default:dirt_with_grass_footsteps", "element:dirt_with_grass_footsteps")
minetest.register_alias("default:dirt_with_snow", "element:dirt_with_snow")
minetest.register_alias("default:gravel", "element:gravel")
minetest.register_alias("default:ice", "element:ice")
minetest.register_alias("default:lava_flowing", "element:lava_flowing")
minetest.register_alias("default:lava_source", "element:lava_source")
minetest.register_alias("default:methane", "element:methane")
minetest.register_alias("default:river_water_flowing", "element:river_water_flowing")
minetest.register_alias("default:river_water_source", "element:river_water_source")
minetest.register_alias("default:sand", "element:sand")
minetest.register_alias("default:sandstone", "element:sandstone")
minetest.register_alias("default:silver_sand", "element:silver_sand")
minetest.register_alias("default:snowblock", "element:snowblock")
minetest.register_alias("default:snow", "element:snow")
minetest.register_alias("default:water_flowing", "element:water_flowing")
minetest.register_alias("default:water_source", "element:water_source")

-- soil
minetest.register_alias("farming:desert_sand_soil", "element:desert_sand_soil")
minetest.register_alias("farming:desert_sand_soil_wet", "element:desert_sand_soil_wet")
minetest.register_alias("farming:soil", "element:soil")
minetest.register_alias("farming:soil_wet", "element:soil_wet")

minetest.register_alias("fire:basic_flame", "element:basic_flame")
minetest.register_alias("fire:permanent_flame", "element:permanent_flame")

minetest.register_alias("weather:snow_cover", "element:snow")
