minetest.register_alias("default:cactus", "plant:cactus")
minetest.register_alias("cactus", "plant:cactus")
minetest.register_alias("default:dry_shrub", "plant:dry_shrub")
minetest.register_alias("default:grass_1", "plant:grass_1")
minetest.register_alias("default:grass_2", "plant:grass_2")
minetest.register_alias("default:grass_3", "plant:grass_3")
minetest.register_alias("default:grass_4", "plant:grass_4")
minetest.register_alias("default:grass_5", "plant:grass_5")
minetest.register_alias("default:junglegrass", "plant:junglegrass")
minetest.register_alias("junglegrass", "plant:junglegrass")
minetest.register_alias("default:papyrus", "plant:papyrus")
minetest.register_alias("papyrus", "plant:papyrus")

minetest.register_alias("farming:wheat", "plant:straw")
--minetest.register_alias("flowers:cotton_plant", "farming:cotton_8") 
--minetest.register_alias("flowers:flower_cotton", "farming:cotton_8")
minetest.register_alias("flowers:cotton", "plant:fibre")
minetest.register_alias("flowers:cotton_wad", "plant:fibre")
--minetest.register_alias("farming:cotton_8", "plant:cotton_8")
minetest.register_alias("farming:string", "material:string")
minetest.register_alias("farming:cotton", "plant:fibre")


minetest.register_alias("farming:carrot", "plant:carrot")
minetest.register_alias("farming:seed_wheat", "plant:wheat_seed")
--minetest.register_alias("farming:seed_cotton", "plant:cotton_seed")
--minetest.register_alias("ethereal:fish_raw", "fishing:fish")
--minetest.register_alias("farming:bread", "food:bread")
minetest.register_alias("farming:potato", "plant:beetroot")
