-- Mapgen

minetest.register_alias("mapgen_tree", "tree:apple_tree_trunk")
minetest.register_alias("mapgen_leaves", "tree:apple_tree_leaves")
minetest.register_alias("mapgen_apple", "tree:apple_fruit")
minetest.register_alias("mapgen_jungletree", "tree:jungletree")
minetest.register_alias("mapgen_jungleleaves", "tree:jungleleaves")
minetest.register_alias("mapgen_pine_tree", "tree:pine_tree")
minetest.register_alias("mapgen_pine_needles", "tree:pine_needles")

-- Aliases for corrected pine node names
minetest.register_alias("default:pinetree", "tree:pine_tree")
minetest.register_alias("default:pinewood", "tree:pine_wood")

minetest.register_alias("default:leaves", "tree:apple_tree_leaves")
minetest.register_alias("default:tree", "tree:apple_tree_trunk")
minetest.register_alias("default:apple", "tree:apple_fruit")
minetest.register_alias("default:jungleleaves", "tree:jungleleaves")
minetest.register_alias("default:jungletree", "tree:jungletree")
minetest.register_alias("default:pine_needles", "tree:pine_needles")
minetest.register_alias("default:pine_tree", "tree:pine_tree")
minetest.register_alias("default:acacia_leaves", "tree:acacia_leaves")
minetest.register_alias("default:acacia_tree", "tree:acacia_tree")

minetest.register_alias("leaves", "tree:apple_tree_leaves")
minetest.register_alias("trunk", "tree:apple_tree_trunk")
minetest.register_alias("tree", "tree:apple_tree_trunk")
minetest.register_alias("apple", "tree:apple_fruit")
minetest.register_alias("wood", "moretrees:beech_planks")
minetest.register_alias("apple_tree_leaves", "tree:apple_tree_leaves")
minetest.register_alias("apple_tree_trunk", "tree:apple_tree_trunk")
minetest.register_alias("apple_tree_wood", "tree:apple_tree_wood")
minetest.register_alias("jungle_leaves", "tree:jungleleaves")
minetest.register_alias("jungleleaves", "tree:jungleleaves")
minetest.register_alias("jungle_trunk", "tree:jungletree")
minetest.register_alias("jungletree", "tree:jungletree")
minetest.register_alias("jungle_wood", "tree:junglewood")
minetest.register_alias("junglewood", "moretrees:jungletree_planks")
minetest.register_alias("pine_leaves", "tree:pine_needles")
minetest.register_alias("pine_trunk", "tree:pine_tree")
minetest.register_alias("pine_wood", "tree:pine_wood")
minetest.register_alias("acacia_leaves", "tree:acacia_leaves")
minetest.register_alias("acacia_trunk", "tree:acacia_tree")
minetest.register_alias("acacia_wood", "tree:acacia_wood")

minetest.register_alias("acorn", "moretrees:acorn")
minetest.register_alias("beech_leaves", "moretrees:beech_leaves")
minetest.register_alias("beech_wood", "moretrees:beech_planks")
minetest.register_alias("beech_trunk", "moretrees:beech_trunk")
minetest.register_alias("birch_leaves", "moretrees:birch_leaves")
minetest.register_alias("birch_wood", "moretrees:birch_planks")
minetest.register_alias("birch_trunk", "moretrees:birch_trunk")
minetest.register_alias("fir_cone", "moretrees:fir_cone")
minetest.register_alias("fir_leaves", "moretrees:fir_leaves")
minetest.register_alias("fir_wood", "moretrees:fir_planks")
minetest.register_alias("fir_trunk", "moretrees:fir_trunk")
minetest.register_alias("jungletree_trunk", "moretrees:jungletree_trunk")
minetest.register_alias("oak_leaves", "moretrees:oak_leaves")
minetest.register_alias("oak_wood", "moretrees:oak_planks")
minetest.register_alias("oak_trunk", "moretrees:oak_trunk")
minetest.register_alias("pine_cone", "moretrees:pine_cone")
minetest.register_alias("spruce_cone", "moretrees:spruce_cone")
minetest.register_alias("spruce_leaves", "moretrees:spruce_leaves")
minetest.register_alias("spruce_wood", "moretrees:spruce_planks")
minetest.register_alias("spruce_trunk", "moretrees:spruce_trunk")
minetest.register_alias("willow_leaves", "moretrees:willow_leaves")
minetest.register_alias("willow_wood", "moretrees:willow_planks")
minetest.register_alias("willow_trunk", "moretrees:willow_trunk")



